# Generated by Django 4.2.6 on 2023-10-08 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkupandappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=100)),
                ('DateAdded', models.DateField(blank=True)),
                ('DateUpdated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=100)),
                ('Disease_count', models.IntegerField()),
                ('DateAdded', models.DateField(blank=True)),
                ('DateUpdated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('desription', models.TextField(blank=True, max_length=100)),
                ('DateAdded', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('Medications', models.CharField(blank=True, max_length=100, null=True)),
                ('Medicalconditions', models.CharField(blank=True, max_length=100, null=True)),
                ('Familyhistory', models.TextField(blank=True, null=True)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recentlabhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fastingbloodsugar', models.CharField(blank=True, max_length=100, null=True)),
                ('Bloodpressure', models.CharField(blank=True, max_length=100, null=True)),
                ('Hba1c', models.FloatField(blank=True, null=True)),
                ('Cholesterol', models.FloatField(blank=True, null=True)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patientinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientAGE', models.IntegerField(blank=True, null=True)),
                ('PatientCOURSE', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientYEARLEVEL', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientGender', models.CharField(blank=True, max_length=100, null=True)),
                ('PatientBirthday', models.CharField(blank=True, max_length=100, null=True)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now_add=True)),
                ('CheckupandappointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.checkupandappointment')),
                ('ContactInformationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.contactinformation')),
                ('MedicalHistoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalhistory')),
                ('RecentlabhistoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.recentlabhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('residence', models.CharField(blank=True, max_length=100)),
                ('bday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('companyname', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('periodfrom', models.DateField(blank=True, null=True)),
                ('periodto', models.DateField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
